name: Java CI with Maven

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Dependency Setup
      run: mvn dependency:tree

    - name: Build Jar File
      run: mvn compile package

    - name: Upload Jar File
      uses: actions/upload-artifact@v3
      with:
          name: jarfile
          path: target/VndustryUtils-1.jar

